/* Workarounds for petalinux configurations */
#ifndef __PLNX_PLATFORM_TOP_H
#define __PLNX_PLATFORM_TOP_H

#define CONFIG_ZYNQ_GPIO

#ifdef CONFIG_SYS_GENERIC_BOARD
# undef CONFIG_SYS_GENERIC_BOARD
#endif

#ifdef CONFIG_FIT
# undef CONFIG_FIT
#endif

#ifdef CONFIG_FIT_VERBOSE
# undef CONFIG_FIT_VERBOSE
#endif

#ifdef CONFIG_SYS_PROMPT
# undef CONFIG_SYS_PROMPT
#endif

#ifdef CONFIG_ZYNQ_SDHCI
# undef CONFIG_ZYNQ_SDHCI
#endif

#ifdef CONFIG_SPI_FLASH_SPANSION
# undef CONFIG_SPI_FLASH_SPANSION
#endif

#ifdef CONFIG_PHYLIB
# undef CONFIG_PHYLIB
#endif

#ifdef CONFIG_ZYNQ_GEM
# undef CONFIG_ZYNQ_GEM
#endif

#ifdef CONFIG_ZYNQ_QSPI
# undef CONFIG_ZYNQ_QSPI
#endif

#ifdef CONFIG_SYS_HZ
# undef CONFIG_SYS_HZ
#endif

#include <configs/platform-auto.h>

#ifdef CONFIG_SYS_MALLOC_LEN
# undef CONFIG_SYS_MALLOC_LEN
#endif
#define CONFIG_SYS_MALLOC_LEN	0x1400000

#ifdef CONFIG_SYS_INIT_RAM_ADDR
# undef CONFIG_SYS_INIT_RAM_ADDR
#endif
#define CONFIG_SYS_INIT_RAM_ADDR	CONFIG_SYS_SDRAM_BASE

#ifdef CONFIG_SYS_INIT_RAM_SIZE
# undef CONFIG_SYS_INIT_RAM_SIZE
#endif
#define CONFIG_SYS_INIT_RAM_SIZE	CONFIG_SYS_MALLOC_LEN

#ifdef CONFIG_ZYNQ_GEM_PHY_ADDR0
# undef CONFIG_ZYNQ_GEM_PHY_ADDR0
#endif
#define CONFIG_ZYNQ_GEM_PHY_ADDR0	1

#ifdef CONFIG_SYS_TEXT_BASE
# undef CONFIG_SYS_TEXT_BASE
#endif
#define CONFIG_SYS_TEXT_BASE	0x4000000

/* additional config setting for Zybo */
#define CONFIG_ZYNQ_USB

#define CONFIG_ZYNQ_I2C0
#define CONFIG_ZYNQ_I2C1
#define CONFIG_SYS_I2C_EEPROM_ADDR_LEN 1
#define CONFIG_CMD_EEPROM
#define CONFIG_ZYNQ_GEM_EEPROM_ADDR    0x50
#define CONFIG_ZYNQ_GEM_I2C_MAC_OFFSET 0xFA
#define CONFIG_DISPLAY
#define CONFIG_I2C_EDID

#if defined(CONFIG_ZYNQ_I2C0) || defined(CONFIG_ZYNQ_I2C1)
#define CONFIG_SYS_I2C_ZYNQ
#endif

/* I2C */
#if defined(CONFIG_SYS_I2C_ZYNQ)
# define CONFIG_CMD_I2C
# define CONFIG_SYS_I2C
# define CONFIG_SYS_I2C_ZYNQ_SPEED             100000
# define CONFIG_SYS_I2C_ZYNQ_SLAVE             0
#endif /* CONFIG_SYS_I2C_ZYNQ */

#ifdef CONFIG_ZYNQ_USB
# define CONFIG_USB_EHCI
# define CONFIG_CMD_USB
# define CONFIG_USB_STORAGE
# define CONFIG_USB_EHCI_ZYNQ
# define CONFIG_USB_ULPI_VIEWPORT
# define CONFIG_USB_ULPI
# define CONFIG_EHCI_IS_TDI
# define CONFIG_USB_MAX_CONTROLLER_COUNT       2

# define CONFIG_CI_UDC           /* ChipIdea CI13xxx UDC */
# define CONFIG_USB_GADGET
# define CONFIG_USB_GADGET_DUALSPEED
# define CONFIG_USB_GADGET_DOWNLOAD
# define CONFIG_SYS_DFU_DATA_BUF_SIZE  0x600000
# define DFU_DEFAULT_POLL_TIMEOUT      300
# define CONFIG_USB_FUNCTION_DFU
# define CONFIG_DFU_RAM
# define CONFIG_USB_GADGET_VBUS_DRAW   2
# define CONFIG_G_DNL_VENDOR_NUM       0x03FD
# define CONFIG_G_DNL_PRODUCT_NUM      0x0300
# define CONFIG_G_DNL_MANUFACTURER     "Xilinx"
# define CONFIG_USB_GADGET
# define CONFIG_USB_CABLE_CHECK
# define CONFIG_CMD_DFU
# define CONFIG_CMD_THOR_DOWNLOAD
# define CONFIG_USB_FUNCTION_THOR
# define CONFIG_DISPLAY_BOARDINFO
#endif /* CONFIG_ZYNQ_USB */

#endif /* __PLNX_PLATFORM_TOP_H */
